<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P2B-69WFNK2" ignored="7" name="Default test" tests="1" failures="1" timestamp="08 Sep 2018 10:40:21 GMT" time="197.731" errors="0">
  <testcase name="dataExcel" time="191.032" classname="Maven.ActionTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Maven.ActionTest.doLogin(ActionTest.java:134)
	at Maven.ActionTest.dataExcel(ActionTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dataExcel -->
  <testcase name="takescreenshotDemo" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- takescreenshotDemo -->
  <testcase name="demoFileupload" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- demoFileupload -->
  <testcase name="seleniumGrid" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- seleniumGrid -->
  <testcase name="demoRobot" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- demoRobot -->
  <testcase name="javascriptDemo" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- javascriptDemo -->
  <testcase name="cookieDemo" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- cookieDemo -->
  <testcase name="demoTest" time="0.0" classname="Maven.ActionTest">
    <ignored/>
  </testcase> <!-- demoTest -->
</testsuite> <!-- Default test -->
